name: CI - RMP Demo Store

on:
  pull_request:
    paths:
      - '**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js (14)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/cache@v2
        id: cache-packages
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-rmp-portal-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache-packages.outputs.cache-hit != 'true'
        run: yarn

      - name: Lint
        run: yarn workspaces run lint

      - name: Build and link dependencies
        run: |
          yarn workspace @rmp-demo-store/seller-portal build:deps
          yarn workspace @rmp-demo-store/seller-portal link:deps

      - name: Pre-commit
        run: yarn workspaces run hooks:pre-commit
